services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: cementeriodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmincementerio
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=desarrollo@google.com
      - PGADMIN_DEFAULT_PASSWORD=delunoalnueve
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json